version: "3.8"

services:
  eventsim:
    build:
      context: ./eventsim
      dockerfile: Dockerfile
    container_name: eventsim
    volumes:
      - ./eventsim/config.json:/src/data/config.json
    command: >
         -c /src/data/config.json
         --start-time "2026-01-01T00:00:00"
         --nusers 1000
         --growth-rate 10
         --kafkaBrokerList kafka:9092
         --continuous
    networks:
      - music-net
    restart: on-failure

networks:
  music-net:
    driver: bridge