dbt_music_stream:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('GCP_BQ_DATASET_NAME') }}"
      threads: 4
      keyfile: "{{ env_var('AIRFLOW_GCP_KEYFILE_PATH_IN_CONTAINER') }}"
      location: asia-southeast1