version: 2

sources:
  - name: raw_gcs
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: "{{ env_var('GCP_BQ_DATASET_NAME') }}"
    tables:
      - name: listen_events
      - name: auth_events
      - name: page_view_events
