version: 2

sources:
  - name: raw_gcs
    database: realestate-492305
    schema: music_stream_warehouse
    tables:
      - name: listen_events
      - name: auth_events
      - name: page_view_events
